-- ################################################################################################
-- Usage of highlighting by render-markdown.nvim can be reviewed at the following location:
-- https://github.com/MeanderingProgrammer/render-markdown.nvim/tree/main/lua/render-markdown/config
-- ################################################################################################

-- Get theme from the current kanagawa colorscheme
-- Theme colors can be reviewed at the following locations:
-- https://github.com/rebelot/kanagawa.nvim/blob/master/lua/kanagawa/themes.lua
-- https://github.com/rebelot/kanagawa.nvim/blob/master/lua/kanagawa/colors.lua
local colors = require("plugins.custom-themes.kanagawa-palette").full

return {
	wave = {
		rmd_H1 = { bg = colors.sumiInk3, fg = colors.waveRed },
		rmd_H2 = { bg = colors.sumiInk3, fg = colors.crystalBlue },
		rmd_H3 = { bg = colors.sumiInk3, fg = colors.oniViolet },
		rmd_H4 = { bg = colors.sumiInk3, fg = colors.autumnYellow },
		rmd_H5 = { bg = colors.sumiInk3, fg = colors.autumnGreen },
		rmd_H6 = { bg = colors.sumiInk3, fg = colors.oniViolet2 },
		rmd_H1Bg = { bg = colors.sumiInk3, fg = colors.waveRed },
		rmd_H2Bg = { bg = colors.sumiInk3, fg = colors.crystalBlue },
		rmd_H3Bg = { bg = colors.sumiInk3, fg = colors.oniViolet },
		rmd_H4Bg = { bg = colors.sumiInk3, fg = colors.autumnYellow },
		rmd_H5Bg = { bg = colors.sumiInk3, fg = colors.autumnGreen },
		rmd_H6Bg = { bg = colors.sumiInk3, fg = colors.oniViolet2 },
		-- rmd_Code = {},
		-- rmd_CodeBorder = {},
		-- rmd_CodeFallback = {},
		-- rmd_CodeInline = {},
		-- rmd_Quote = {},
		-- rmd_Quote1 = {},
		-- rmd_Quote2 = {},
		-- rmd_Quote3 = {},
		-- rmd_Quote4 = {},
		-- rmd_Quote5 = {},
		-- rmd_Quote6 = {},
		-- rmd_InlineHighlight = {},
		-- rmd_Bullet = {},
		-- rmd_Dash = {},
		-- rmd_Sign = {},
		-- rmd_Math = {},
		-- rmd_Indent = {},
		-- rmd_HtmlComment = {},
		-- rmd_Link = {},
		-- rmd_WikiLink = {},
		-- rmd_Unchecked = {},
		-- rmd_Checked = {},
		-- rmd_Todo = {},
		-- rmd_TableHead = {},
		-- rmd_TableRow = {},
		-- rmd_TableFill = {},
		-- rmd_Success = {},
		-- rmd_Info = {},
		-- rmd_Hint = {},
		-- rmd_Warn = {},
		-- rmd_Error = {},
	},
	dragon = {
		rmd_H1 = { bg = colors.sumiInk3, fg = colors.dragonRed },
		rmd_H2 = { bg = colors.sumiInk3, fg = colors.dragonBlue },
		rmd_H3 = { bg = colors.sumiInk3, fg = colors.dragonPink },
		rmd_H4 = { bg = colors.sumiInk3, fg = colors.dragonYellow },
		rmd_H5 = { bg = colors.sumiInk3, fg = colors.dragonGreen },
		rmd_H6 = { bg = colors.sumiInk3, fg = colors.dragonTeal },
		rmd_H1Bg = { bg = colors.sumiInk3, fg = colors.dragonRed },
		rmd_H2Bg = { bg = colors.sumiInk3, fg = colors.dragonBlue },
		rmd_H3Bg = { bg = colors.sumiInk3, fg = colors.dragonPink },
		rmd_H4Bg = { bg = colors.sumiInk3, fg = colors.dragonYellow },
		rmd_H5Bg = { bg = colors.sumiInk3, fg = colors.dragonGreen },
		rmd_H6Bg = { bg = colors.sumiInk3, fg = colors.dragonTeal },
		-- rmd_Code = {},
		-- rmd_CodeBorder = {},
		-- rmd_CodeFallback = {},
		-- rmd_CodeInline = {},
		-- rmd_Quote = {},
		-- rmd_Quote1 = {},
		-- rmd_Quote2 = {},
		-- rmd_Quote3 = {},
		-- rmd_Quote4 = {},
		-- rmd_Quote5 = {},
		-- rmd_Quote6 = {},
		-- rmd_InlineHighlight = {},
		-- rmd_Bullet = {},
		-- rmd_Dash = {},
		-- rmd_Sign = {},
		-- rmd_Math = {},
		-- rmd_Indent = {},
		-- rmd_HtmlComment = {},
		-- rmd_Link = {},
		-- rmd_WikiLink = {},
		-- rmd_Unchecked = {},
		-- rmd_Checked = {},
		-- rmd_Todo = {},
		-- rmd_TableHead = {},
		-- rmd_TableRow = {},
		-- rmd_TableFill = {},
		-- rmd_Success = {},
		-- rmd_Info = {},
		-- rmd_Hint = {},
		-- rmd_Warn = {},
		-- rmd_Error = {},
	},
}
