# Kanagawa terminal colorscheme
BLACK="#16161D" # sumiInk0
RED="#C34043" # autumnRed
GREEN="#76946A" # autumnGreen
YELLOW="#C0A36E" # boatYellow2
BLUE="#7E9CD8" # crystalBlue
MAGENTA="#957FB8" # oniViolet
CYAN="#6A9589" # waveAqua1
WHITE="#C8C093" # oldWhite
BRIGHT_BLACK="#727169" # fujiGray
BRIGHT_RED="#E82424" # samuraiRed
BRIGHT_GREEN="#98BB6C" # springGreen
BRIGHT_YELLOW="#E6C384" # carpYellow
BRIGHT_BLUE="#7FB4CA" # springBlue
BRIGHT_MAGENTA="#938AA9" # springViolet1
BRIGHT_CYAN="#7AA89F" # waveAqua2
BRIGHT_WHITE="#DCD7BA" # fujiWhite
EXTENDED1="#FFA066" # surimiOrange
EXTENDED2="#FF5D62" # peachRed

# Nerd Font Characters
HALF_ROUND_OPEN="#(printf '\uE0B6')"
HALF_ROUND_CLOSED="#(printf '\uE0B4')"
TRIANGLE_OPEN="#(printf '\uE0B2')"
TRIANGLE_CLOSE="#(printf '\uE0B0')"

# Set basic colors of the status bar
set-option -g status-style bg=default,fg=default

# Show the window list centered on the Statusbar
set-option -g status-justify absolute-centre

# Style and set the contents of the left section
set-option -g status-left "#[fg=${BLACK},bg=${MAGENTA}] Session: #S #[fg=${MAGENTA},bg=default]${HALF_ROUND_CLOSED}"

# Style and set the contents of the right section
set-option -g status-right "#[fg=${MAGENTA},bg=default]${HALF_ROUND_OPEN}#[fg=${BLACK},bg=${MAGENTA}] Tmux on: #h "

# Set the max length of the left and right sections
set-option -g status-left-length 100
set-option -g status-right-length 100

# Style and set the content for the inactive windows
set-option -g window-status-format " #I#[fg=${MAGENTA}]:#[fg=default]#W "

# Style and set content for the active window
set-option -g window-status-current-format "#[fg=${CYAN},bg=default]${HALF_ROUND_OPEN}#[fg=default,bg=${CYAN}]#I#[fg=${RED}]:#[fg=default]#W#[fg=${CYAN}, bg=default]${HALF_ROUND_CLOSED}"

# Remove the separator between the window list items, as the style already
# incorporates a separator.
set-option -g window-status-separator ""

